### ISSUE TITLE
Starling Bank SVG resources with MIT (or other liberal) license

### ISSUE THREAD

**Issue by pranasblk** [starlingbank/developer-resources#10]
As I 3rd party developer I'd love to get some logos I can use in our software. 

Thanks!

**Comment by icecreamhead** [comment]
Hi Pranas, you can find our [media kit](https://www.starlingbank.com/media/) on this page of our website.

**Comment by icecreamhead** [comment]
Hi Pranas, you can find our [media kit](https://www.starlingbank.com/media/) on this page of our website.
