### ISSUE TITLE
:squirrel: emoji no longer rendering.

### ISSUE THREAD

**Issue by shymega** [starlingbank/developer-resources#4]
The `:squirrel:` emoji [here](https://github.com/starlingbank/developer-resources/blob/master/README.md#useful-links) is no longer rendering. Looks like it may have been removed from GitHub.. although I thought it was part of the Unicode standard.

**Comment by domdomegg** [comment]
Thanks for raising this, fixed in #5 :)

**Comment by shymega** [comment]
Thanks for fixing it. No problem :+1:
